services:
  migrate:
    build:
      context: .
      target: migrate
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: .
      target: api
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  db:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
